### ISSUE TITLE
Separating view and machine learning code

### ISSUE THREAD

**Issue by daviddao** [piximi/application#17]
The front end looks amazing - we should take some time to talk about a good API specification to separate view from machine learning (currently it's not that clean). Maybe it makes sense to even split them into two GitHub repositories. 

It would be nice to have either an API specification or design doc on how we want to include AI modules. I could spend some time (with another student at ETH Zurich) working on the ML backend side.

**Comment by 0x00b1** [comment]
I agree! Ideally everything except the event handler could be moved inside a new package.
